services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  meter:
    build: .
    command: python main_meter.py
    depends_on:
      - rabbitmq

  pv_simulator:
    build: .
    command: python main_pv.py
    depends_on:
      - rabbitmq

volumes:
  data:
